### PR TITLE
Fixed site fields missing from node/media form after site-install.

### PR DESCRIPTION
**Pull request by sonnykt**
https://digital-engagement.atlassian.net/browse/DDS-235

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

### CODE REVIEW

**Comment by anthony-malkoun** [comment]
@sonnykt this looks fine to me. I would like a test around this for a new install. Any thoughts on how to implement this?

**Comment by sonnykt** [comment]
> @sonnykt this looks fine to me. I would like a test around this for a new install. Any thoughts on how to implement this?

not sure how your scaffold install a new site, but can you configure it to use this PR as patch before running site-install?

**Comment by anthony-malkoun** [comment]
> > @sonnykt this looks fine to me. I would like a test around this for a new install. Any thoughts on how to implement this?
> 
> not sure how your scaffold install a new site, but can you configure it to use this PR as patch before running site-install?

It certainly can. More thinking, where should a test for this live (talking about a behat test)? Does it live with this module or should it live with the scaffold in your opinion?

**Comment by sonnykt** [comment]
> > > @sonnykt this looks fine to me. I would like a test around this for a new install. Any thoughts on how to implement this?
> > 
> > 
> > not sure how your scaffold install a new site, but can you configure it to use this PR as patch before running site-install?
> 
> It certainly can. More thinking, where should a test for this live (talking about a behat test)? Does it live with this module or should it live with the scaffold in your opinion?

Not sure how it can be tested with behat. As tide_site does not come with any content type on both `suggest` and `no-suggest` mode, it relies on the `test` content type from `tide_test`. The issue is that `tide_test`is not installed by `tide` profile but by `dev-tools` after the site has been installed successfully. At that point, the issue no longer occurs hence the test would be pointless.

**Review by anthony-malkoun — APPROVED** [review]
Tested on a clean site install at https://github.com/dpc-sdp/baywatch/pull/39

**Pull request merged**
