### PR TITLE
added new fields

### PR DESCRIPTION
**Pull request by yeniatencio**
Ticket: https://digital-vic.atlassian.net/browse/SD-130
BE testing link: https://nginx-php.pr-429.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
Change:

Updated site app favicon field.
Create a site app icon and short name fields.

Screenshot 2024-09-04 at 11 33 08 am

### CODE REVIEW

**Comment by dylankelly** [comment]
@anthony-malkoun can you please review this? its blocking the next release

**Review by anthony-malkoun — APPROVED** [review]
Hi @yeniatencio just a config PR mostly so looks good to me. Update hook is using `mergeDeep` which is good to see 👍

**Comment by anthony-malkoun** [comment]
@yeniatencio / @vincent-gao / @MdNadimHossain a further note on this. Do config only PRs need a review process like other PRs? Is there some sort of process or checkbox in the PR description we can use to make these ones a bit quicker? Let's discuss in our catch up on Tuesday.

**Comment by MdNadimHossain** [comment]
> @yeniatencio / @vincent-gao / @MdNadimHossain a further note on this. Do config only PRs need a review process like other PRs? Is there some sort of process or checkbox in the PR description we can use to make these ones a bit quicker? Let's discuss in our catch up on Tuesday.

@anthony-malkoun there isn't any process right now. Also only config export is good to merge, but if there is an update hook, I think at least it should get a quick CR

**Comment by dylankelly** [comment]
@MdNadimHossain this has passed QA - please merge

**Pull request merged**
